set(TARGET llama-cuda-pinmem)
add_executable(${TARGET} llama-cuda-pinmem.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE common llama ${CMAKE_THREAD_LIBS_INIT})
if (GGML_CUDA)
    find_package(CUDAToolkit REQUIRED)
    target_link_libraries(${TARGET} PRIVATE CUDA::cudart)
endif()
target_compile_features(${TARGET} PRIVATE cxx_std_11)
